apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ supermario_ingress.name }}
  namespace: {{ supermario_namespace }}
spec:
  rules:
  - host: {{ supermario_ingress.host }}
    http:
      paths:
      - pathType: {{ supermario_ingress.pathType }}
        path: {{ supermario_ingress.path }}
        backend:
          service:
            name: {{ supermario_service.name }}
            port:
              number: 80